name: Release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout repository
        uses: actions/checkout@v3
      -
        name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake libglew-dev libglfw3-dev
      -
        name: Build artifacts
        run: |
          mkdir build-release
          cmake -D CMAKE_BUILD_TYPE=Release -B build-release
          cmake --build build-release -- -j $(($(nproc) * 3 / 4))
      -
        name: Create release
        id: create_release
        uses: actions/create-release@v1
        with:
          draft: false
          prerelease: false
          release_name: ${{ github.ref }}
          tag_name: ${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
      -
        name: Upload artifacts
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build-release/Mandelbrot
          asset_name: Mandelbrot
          asset_content_type: application/octet-stream
        env:
          GITHUB_TOKEN: ${{ github.token }}
